### ISSUE TITLE
Config not showing

### ISSUE THREAD

**Issue by kirsenn** [andrey-yantsen/yandex-cloud-vpn#5]
Hello! I'm trying to create a new wireguard config, i'm running do.sh, server is booted up ok, but there is no config presented after script is finished. There is no errors out as well
Output:
```
denis.kirsa@Deniss-MacBook-Pro ~ % ./do.sh
Booting up a new server...
...1s...6s...12s...17s...23s...done (25s)
New instance IP address: 51.250.90.219
Configuring the server...%
denis.kirsa@Deniss-MacBook-Pro ~ % 
```

**Comment by andrey-yantsen** [comment]
@kirsenn this could be happening because sometimes the cloud server takes time to boot up. Can you try increasing [the delay](https://github.com/andrey-yantsen/yandex-cloud-vpn/blob/240f84ef8196ad7ff19c33d23eb38295fe02ad2b/do.sh#L101) to, let's say, 60 seconds and give it another go?

**Comment by andrey-yantsen** [comment]
P.S. You'd need to either manually remove the previously created server or run the script with `-d` flag to remove it automatically.

**Comment by kirsenn** [comment]
I've increased to 60 sec and it works now, thank you!

```
denis.kirsa@Deniss-MacBook-Pro ~ % ./do.sh
Booting up a new server...
...1s...6s...11s...16s...22s...27s...32s...done (32s)
New instance IP address: 158.160.52.36
Configuring the server...done!
Copy the following config to the client#1

[Interface]
...
...
```

**Comment by andrey-yantsen** [comment]
I'll keep the issue open for now, if you don't mind :)

**Comment by andrey-yantsen** [comment]
Ok, now, instead of blindly waiting for 30 seconds before the connection attempt, there's slightly more logic under the hood.

By default, the script makes 12 connection attempts, with a 5-second pause between them. Which translates to a 60 seconds timeout. The number of attempts can be changed via the `-i` argument, and the delay/timeout between the attempts can be changed via the `-t` argument.

And yeah, it now has some better error reporting in case of a timeout :)

Thank you for reminding me about this issue, Denis! :)
